name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: https://www.memodify.com
    env:
      NEXT_PUBLIC_GOOGLE_ANALYTICS_MEASUREMENT_ID: ${{ secrets.GOOGLE_ANALYTICS_MEASUREMENT_ID }}
      NEXT_PUBLIC_LIVEDEMO_URL: ${{ secrets.NEXT_PUBLIC_LIVEDEMO_URL }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: touch ./out/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: www.memodify.com
